// SPDX-License-Identifier: Apache-2.0
import Foundation

/// Resolves paths to binaries shipped inside the app bundle.
///
/// `adb` is shipped as two universal-ish binaries (one per arch) under
/// `Resources/adb/<arch>/adb`. The Quest client APK is shipped as
/// `Resources/quest/fuvr-quest.apk`.
///
/// During development the binaries may not be present (they are downloaded
/// by `scripts/fetch-adb.sh` and the APK is produced by `./gradlew
/// assembleDebug`). The resolver therefore returns `nil` and the UI surfaces
/// a clear error rather than crashing.
public enum BundledTools {
    public enum LookupError: Error, CustomStringConvertible {
        case adbMissing(arch: String, expectedPath: String)
        case apkMissing(expectedPath: String)
        case notExecutable(path: String)

        public var description: String {
            switch self {
            case .adbMissing(let arch, let path):
                return "adb (\(arch)) is not bundled. Expected at: \(path). " +
                       "Run `scripts/fetch-adb.sh` from the repo root to populate it."
            case .apkMissing(let path):
                return "Quest APK is not bundled. Expected at: \(path). " +
                       "Build it with `./gradlew assembleDebug` then re-run the bundling step."
            case .notExecutable(let path):
                return "File at \(path) is not executable. chmod +x it or re-run fetch-adb.sh."
            }
        }
    }

    /// Detect the host CPU architecture as a stable string ("arm64" / "x86_64").
    public static var hostArch: String {
        var sysinfo = utsname()
        guard uname(&sysinfo) == 0 else { return "unknown" }
        let raw = withUnsafePointer(to: &sysinfo.machine) {
            $0.withMemoryRebound(to: CChar.self, capacity: Int(_SYS_NAMELEN)) {
                String(cString: $0)
            }
        }
        // Apple Silicon reports "arm64", Intel reports "x86_64".
        return raw == "arm64" || raw == "x86_64" ? raw : raw
    }

    /// Returns a URL to the bundled `adb` for the host CPU architecture.
    public static func adbURL() throws -> URL {
        let arch = hostArch
        // First try Bundle.module (SwiftPM). Fall back to walking from the
        // executable URL so that an Xcode-generated bundle still works.
        let candidates = searchRoots().flatMap { root -> [URL] in
            [
                root.appendingPathComponent("Resources/adb/\(arch)/adb"),
                root.appendingPathComponent("adb/\(arch)/adb"),
                root.appendingPathComponent("adb_\(arch)"),
            ]
        }
        let fm = FileManager.default
        for url in candidates where fm.fileExists(atPath: url.path) {
            guard fm.isExecutableFile(atPath: url.path) else {
                throw LookupError.notExecutable(path: url.path)
            }
            return url
        }
        throw LookupError.adbMissing(arch: arch, expectedPath: candidates.first?.path ?? "<unknown>")
    }

    /// Returns a URL to the bundled Quest APK.
    public static func questApkURL() throws -> URL {
        let candidates = searchRoots().flatMap { root -> [URL] in
            [
                root.appendingPathComponent("Resources/quest/fuvr-quest.apk"),
                root.appendingPathComponent("quest/fuvr-quest.apk"),
                root.appendingPathComponent("fuvr-quest.apk"),
            ]
        }
        let fm = FileManager.default
        for url in candidates where fm.fileExists(atPath: url.path) {
            return url
        }
        throw LookupError.apkMissing(expectedPath: candidates.first?.path ?? "<unknown>")
    }

    /// The Android package + activity to launch on the headset.
    public static let questPackage = "com.fuvr.quest"
    public static let questActivity = "com.fuvr.quest.MainActivity"

    // MARK: - Private

    private static func searchRoots() -> [URL] {
        var roots: [URL] = []
        // Bundle.module is generated by SwiftPM when the target declares
        // resources. Fall through gracefully if it does not exist.
        #if SWIFT_PACKAGE
        roots.append(Bundle.module.bundleURL)
        roots.append(Bundle.module.resourceURL ?? Bundle.module.bundleURL)
        #endif
        // Xcode-style bundle (Mac.app/Contents/Resources/...)
        let main = Bundle.main
        roots.append(main.bundleURL)
        if let r = main.resourceURL { roots.append(r) }
        // Repo-relative fallback for `swift run` in development.
        let cwd = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        roots.append(cwd.appendingPathComponent("mac-app/Sources/FuVRControl"))
        roots.append(cwd)
        return roots
    }
}
